### ISSUE TITLE
Replace debug with print as the former is not supported by recent version of WireShark

### ISSUE THREAD

**Issue by kydos** [cguimaraes/zenoh-dissector#1]
```debug``` has been removed on recent version of Wireshark, it should be replaced by ```print```.

**Comment by cguimaraes** [comment]
This issue should be revisited to support debug in both Wireshark < 3.0 and >= 3.0.
Print messages are not working on Wireshark < 3.0

```
Wireshark 3.0.0 Release Notes
 - Lua: the various logging functions (debug, info, message, warn and critical) have been removed. Use the print function instead for debugging purposes.
```

**Comment by cguimaraes** [comment]
Closing this issue for now, since no debug messages will be included in the future.
