### ISSUE TITLE
Data messages not recognize

### ISSUE THREAD

**Issue by expploitt** [cguimaraes/zenoh-dissector#10]
Hello! I was testing the dissector and I think that some messages are not working. When I see the data messages of zenoh, I only can see:

![imagen](https://user-images.githubusercontent.com/75727913/118665177-633f6600-b7f2-11eb-9b11-8135d0cbfde2.png)

**Comment by cguimaraes** [comment]
Hi @expploitt !
Could you attach the pcap you are trying to decode, so I can use it to debug the problem?
Thanks.

**Comment by expploitt** [comment]
Okey @cguimaraes. I will repeated the experiment and I will send you the pcap. I was still trying some examples and I don't well how wireshark dissector works, but I think that the flags in the .lua are not the same as the msg.rs from zenoh.

For example, in the image below, the PeerId is 0x01, but in the documentation is 0x20.

![imagen](https://user-images.githubusercontent.com/75727913/118993497-d9c09d00-b985-11eb-86c9-e14fbd2f3b24.png)
 This is the pcap of the pub to zenoh router that I tested, the peerId is in the CLOSE message. ([zenoh_pcap.zip](https://github.com/cguimaraes/zenoh-dissector/files/6516607/zenoh_pcap.zip))

**Comment by cguimaraes** [comment]
Thanks for the pcap. I will fix it as soon as I can.

Regarding the aspect w.r.t. the flags, it really depends on whether a bitshift is being done or not during the decoding. Still, I am not looking at the rust code now to be 100% sure, but I will double check it.

**Comment by expploitt** [comment]
I figure out that you use the flag number using only three bits, so, I
think that it is correct, because you put all the flags in the same number.

Also, please, check the SCOUT message, because I think that is it not being
decoded.

Thanks!

**Comment by cguimaraes** [comment]
@expploitt I was trying the pcap you attached, and everything decodes correctly.
Did you checkout the last changes?

**Comment by cguimaraes** [comment]
With your other pcap in #11, I was able to fix this issue ([#553b7f9](https://github.com/cguimaraes/zenoh-dissector/commit/553b7f9e9f3cb9d99cd37d7e83c5ce9cc9ed4b6f)) which was related to UDP and fragmentation.
I am closing this issue. Thanks @expploitt
