### ISSUE TITLE
SCOUT and HELLO messages

### ISSUE THREAD

**Issue by expploitt** [cguimaraes/zenoh-dissector#11]
I figure out that the SCOUT and HELLO messages never were showed in wireshark, so I try to discover why. I've never program in lua, so I haven't reviewed the code from the dissector. However, I try to see what could be the reason.

The problem with the SCOUT message I think that is due to a bad decoding. 

![imagen](https://user-images.githubusercontent.com/75727913/119022162-97f12000-b9a0-11eb-81fd-fcc5385ebf62.png)

The SCOUT message is a multicast UDP frame.
7 6 5 4 3 2 1 0
+-+-+-+-+-+-+-+-+
|X|W|I|  SCOUT  |
+-+-+-+-+-------+
~      what     ~ if W==1 -- Otherwise implicitly scouting for Brokers
+---------------+

 As it can be seen in the image, the zenoh protocol payload is 0x61 and 0x01.

1. 0x61 -> 0110 0001 -> | X | W | I |  SCOUT  | -> where W and I are flags and SCOUT has the id=0001
2. 0x01 -> 0000 0001 -> is the "what" field.

The problem with the HELLO message is because you always map the port 7447, but the communication of this message use other random ports (one of them is the same used in the SCOUT message).

![imagen](https://user-images.githubusercontent.com/75727913/119023516-4c3f7600-b9a2-11eb-8b52-99a9da43c570.png)

The HELLO message has the following structure.

7 6 5 4 3 2 1 0
+-+-+-+-+-+-+-+-+
|L|W|I|  HELLO  |
+-+-+-+-+-------+
~    peer-id    ~ if I==1
+---------------+
~    whatami    ~ if W==1 -- Otherwise it is from a Broker
+---------------+
~    Locators   ~ if L==1 -- Otherwise src-address is the locator
+---------------+

As you can see in the image, the 0xa2 is the HELLO message with the flags L=1 and I=1 and then comes with the peer-id and the locators.

Maybe a way to achieve decoding this message with the ZENOH dissector is to get the src port of the SCOUT message and get the UDP message that has this port as dest port...

I attach the pcap with the example. If I can help you there is no problem! 
[scout_hello..zip](https://github.com/cguimaraes/zenoh-dissector/files/6517836/scout_hello.zip)

Thanks,

Moises

**Comment by cguimaraes** [comment]
This is fixed in #10 .
However, with the provided capture some issues are happening while decoding LinkStateList message (#12).
Thanks @expploitt
