### ISSUE TITLE
WHATAMI should be replaced by MSG_ID

### ISSUE THREAD

**Issue by kydos** [cguimaraes/zenoh-dissector#3]
In zenoh ```whatami``` (ahat am I) has  a special meeting on ```scout``` and ```hello``` messages, as a consequence it would be best to replace it with msgid/MSGID.

**Comment by cguimaraes** [comment]
Solved by @kydos in [9f7321e](https://github.com/cguimaraes/zenoh-dissector/commit/9f7321e4b8426f0254f5c3f1175a39a95c2a94dc)
