### ISSUE TITLE
Add length information in displayed fields

### ISSUE THREAD

**Issue by Mallets** [cguimaraes/zenoh-dissector#6]
When operating over TCP, zenoh prepends 2 bytes to indicate the total length of the frame to read. It would be great if this information is shown in the dissector. On the other hand, these two bytes will not be present in case of UDP.

**Comment by cguimaraes** [comment]
Complemented @Mallets pull request with commit [#a50a599](https://github.com/cguimaraes/zenoh-dissector/commit/a50a59933e4905b1b355618fade650ea9566bda6)
